### PR TITLE
Add support for Azure OpenAI, Palm, Replicate, Sagemaker (100+LLMs) - using litellm

### PR DESCRIPTION
**Pull request by ishaan-jaff**
This PR adds support for the above mentioned LLMs using LiteLLM https://github.com/BerriAI/litellm/ 
Example
```python
from litellm import completion

## set ENV variables
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion("command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
Noticed the readme mentioned this and I thought adding support for more LLMs will be beneficial to pick which LLM is best for the selected task

>  cases where multiple generative components work together or are called in autoregressive feedback loops, the system as a whole may need to be fit to the target distribution, which in addition to ML training may involve A/B testing between API-identical subsystems and the refinement of simple generative components into complex algorithmic flows that structure the generation process.

**Comment by ishaan-jaff** [comment]
@lcrh @nathanmartz can I get a review on this pr ? 

happy to add testing/docs if this initial commit looks good

**Comment by lcrh** [comment]
Thanks for the PR. Looks cool, I'll try to get around to it soon.

**Comment by lcrh** [comment]
Hi, I took a look. The `litellm` package looks very cool, but I think for now we'd like to keep the example code free from dependencies. Since people are asked to provide their API keys to run the examples, it's best if the path of those keys is as transparent as possible.

I'm thinking about creating a separate example that uses litellm to a/b test various LLMs for a given task, but that's a bit further down the road.

In any case, I appreciate the PR.

**Comment by ishaan-jaff** [comment]
@lcrh curious why a/b test LLMs for a given task ?

**Pull request closed without merging**
